name: 测速

on:
  schedule:
    - cron: "*/5 22-23,0-16 * * *"
    
  workflow_dispatch:

jobs:
  fetch_and_upload_data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Run script
      run: node main.js
      
    - name: Set up Git
      run: |
        git config --global user.name 'gushishang[bot]'
        git config --global user.email 'xiegushi2022@outlook.com'
        git add .
        git commit -m "测速"
          
    - name: Pushing to production branch
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
              
